### ISSUE TITLE
关于推理

### ISSUE THREAD

**Issue by huangChengz** [FreedomIntelligence/GrammarGPT#1]
下载https://huggingface.co/FreedomIntelligence/GrammarGPT/tree/main中的权重跑generate.py推理报错
OSError: Can't load tokenizer for 'F:\code\GrammarGPT\path'. make sure 'F:\code\GrammarGPT\path' is the correct path to a directory containing all relevant files for a BloomTokenizerFast tokenizer.
希望得到解答 谢谢~

**Comment by YaxinFAN1** [comment]
你好，感谢对我们工作的关注，缺失的文件已上传。https://huggingface.co/FreedomIntelligence/GrammarGPT/blob/main/tokenizer.json
https://huggingface.co/FreedomIntelligence/GrammarGPT/blob/main/tokenizer_config.json
