### ISSUE TITLE
OSError: Can't load tokenizer for './saved model'

### ISSUE THREAD

**Issue by dedebao** [FreedomIntelligence/GrammarGPT#3]
when I execute python generate.py,I encountered an error like this:
OSError: Can't load tokenizer for './saved model'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './saved model' is the correct path to a directory containing all relevant files for a BloomTokenizerFast tokenizer.
I successfully execute python finetune.py and generated a folder named saved model,the folder has files:
drwxr-xr-x  2 root root       4096 Dec  1 16:33 checkpoint-2/
-rw-r--r--  1 root root        828 Dec  1 17:21 config.json
-rw-r--r--  1 root root        132 Dec  1 17:21 generation_config.json
-rw-r--r--  1 root root 4916004776 Dec  1 17:22 model-00001-of-00006.safetensors
-rw-r--r--  1 root root 4833124624 Dec  1 17:22 model-00002-of-00006.safetensors
-rw-r--r--  1 root root 4833124648 Dec  1 17:22 model-00003-of-00006.safetensors
-rw-r--r--  1 root root 4833124696 Dec  1 17:22 model-00004-of-00006.safetensors
-rw-r--r--  1 root root 4833124696 Dec  1 17:22 model-00005-of-00006.safetensors
-rw-r--r--  1 root root 4027603880 Dec  1 17:22 model-00006-of-00006.safetensors
-rw-r--r--  1 root root      31840 Dec  1 17:23 model.safetensors.index.json

the checkpoint-2 folder has files:
-rw-r--r-- 1 root root         828 Dec  1 17:19 config.json
-rw-r--r-- 1 root root         132 Dec  1 17:19 generation_config.json
-rw-r--r-- 1 root root  4916004776 Dec  1 17:19 model-00001-of-00006.safetensors
-rw-r--r-- 1 root root  4833124624 Dec  1 17:19 model-00002-of-00006.safetensors
-rw-r--r-- 1 root root  4833124648 Dec  1 17:20 model-00003-of-00006.safetensors
-rw-r--r-- 1 root root  4833124696 Dec  1 17:20 model-00004-of-00006.safetensors
-rw-r--r-- 1 root root  4833124696 Dec  1 17:20 model-00005-of-00006.safetensors
-rw-r--r-- 1 root root  4027603880 Dec  1 17:20 model-00006-of-00006.safetensors
-rw-r--r-- 1 root root       31840 Dec  1 17:20 model.safetensors.index.json
-rw-r--r-- 1 root root 56552436457 Dec  1 17:21 optimizer.pt
-rw-r--r-- 1 root root       13990 Dec  1 17:21 rng_state.pth
-rw-r--r-- 1 root root        1064 Dec  1 17:21 scheduler.pt
-rw-r--r-- 1 root root         658 Dec  1 17:21 trainer_state.json
-rw-r--r-- 1 root root        4536 Dec  1 17:20 training_args.bin

Just to add：when I execute python finetune.py,Screen Output：
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:15<00:00,  3.11s/it]
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1061/1061 [00:00<00:00, 1527.01 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:00<00:00, 1934.00 examples/s]
Detected kernel version 4.15.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
  0%|                                                                                                                                                | 0/2 [00:00<?, ?it/s]You're using a BloomTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
{'eval_loss': 0.3425457775592804, 'eval_runtime': 451.8461, 'eval_samples_per_second': 1.107, 'eval_steps_per_second': 0.024, 'epoch': 0.7}                                
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [40:42<00:00, 979.78s/it]Could not locate the best model at ./saved model/checkpoint-2/pytorch_model.bin, if you are running a distributed training on multiple nodes, you should activate `--save_on_each_node`.
{'train_runtime': 2575.4067, 'train_samples_per_second': 0.412, 'train_steps_per_second': 0.001, 'train_loss': 1.0887482166290283, 'epoch': 0.7}                           
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [42:55<00:00, 1287.70s/it]

 If there's a warning about missing keys above, please disregard :)

I want to know which step I made a mistake and ended up reporting this error：OSError: Can't load tokenizer for './saved model'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './saved model' is the correct path to a directory containing all relevant files for a BloomTokenizerFast tokenizer.

**Comment by dedebao** [comment]
my lib environment:
Package                   Version
------------------------- ------------
accelerate                0.24.1
aiofiles                  23.2.1
aiohttp                   3.9.0
aiosignal                 1.3.1
altair                    5.1.2
annotated-types           0.6.0
anyio                     3.7.1
appdirs                   1.4.4
asttokens                 2.4.1
async-timeout             4.0.3
attrs                     23.1.0
backcall                  0.2.0
bitsandbytes              0.41.2.post2
black                     23.11.0
certifi                   2023.11.17
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
contourpy                 1.1.1
cycler                    0.12.1
datasets                  2.15.0
decorator                 5.1.1
dill                      0.3.7
exceptiongroup            1.2.0
executing                 2.0.1
fastapi                   0.104.1
ffmpy                     0.3.1
filelock                  3.13.1
fire                      0.5.0
fonttools                 4.45.1
frozenlist                1.4.0
fsspec                    2023.10.0
gradio                    4.7.1
gradio_client             0.7.0
h11                       0.14.0
httpcore                  1.0.2
httpx                     0.25.1
huggingface-hub           0.19.4
idna                      3.4
importlib-resources       6.1.1
install                   1.3.5
ipython                   8.12.3
jedi                      0.19.1
Jinja2                    3.1.2
jsonschema                4.20.0
jsonschema-specifications 2023.11.1
kiwisolver                1.4.5
loralib                   0.1.2
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib                3.7.4
matplotlib-inline         0.1.6
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.0.4
multiprocess              0.70.15
mypy-extensions           1.0.0
networkx                  3.1
numpy                     1.24.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.18.1
nvidia-nvjitlink-cu12     12.3.101
nvidia-nvtx-cu12          12.1.105
orjson                    3.9.10
packaging                 23.2
pandas                    2.0.3
parso                     0.8.3
pathspec                  0.11.2
peft                      0.6.3.dev0
pexpect                   4.8.0
pickleshare               0.7.5
Pillow                    10.1.0
pip                       23.3.1
pkgutil_resolve_name      1.3.10
platformdirs              4.0.0
prompt-toolkit            3.0.41
psutil                    5.9.6
ptyprocess                0.7.0
pure-eval                 0.2.2
pyarrow                   14.0.1
pyarrow-hotfix            0.6
pydantic                  2.5.2
pydantic_core             2.14.5
pydub                     0.25.1
Pygments                  2.17.2
pyparsing                 3.1.1
python-dateutil           2.8.2
python-multipart          0.0.6
pytz                      2023.3.post1
PyYAML                    6.0.1
referencing               0.31.0
regex                     2023.10.3
requests                  2.31.0
rich                      13.7.0
rpds-py                   0.13.1
safetensors               0.4.0
scipy                     1.10.1
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                68.0.0
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.0
stack-data                0.6.3
starlette                 0.27.0
sympy                     1.12
termcolor                 2.3.0
tokenize-rt               5.2.0
tokenizers                0.15.0
tomli                     2.0.1
tomlkit                   0.12.0
toolz                     0.12.0
torch                     2.1.1
tqdm                      4.66.1
traitlets                 5.13.0
transformers              4.35.2
triton                    2.1.0
typer                     0.9.0
typing_extensions         4.8.0
tzdata                    2023.3
urllib3                   2.1.0
uvicorn                   0.24.0.post1
wcwidth                   0.2.12
websockets                11.0.3
wheel                     0.41.2
xxhash                    3.4.1
yarl                      1.9.3
zipp                      3.17.0

**Comment by dexter-lib** [comment]
the same error

**Comment by YaxinFAN1** [comment]
hi, sry for the late reply. 

put the following two file [tokenizer.json](https://huggingface.co/FreedomIntelligence/GrammarGPT/blob/main/tokenizer.json) and [tokenizer_config](https://huggingface.co/FreedomIntelligence/GrammarGPT/blob/main/tokenizer_config.json) into your saved_model dir may help to solve the problem.  

If you have any question, please feel free to email me. 
My email address : yxfansuda@stu.suda.edu.cn
