### ISSUE TITLE
requirements.txt中git+https://github.com/huggingface/peft.git含义

### ISSUE THREAD

**Issue by lizhao-8202** [FreedomIntelligence/GrammarGPT#6]
咨询下。在requirements.txt中，有git+https://github.com/huggingface/peft.git
是表示在机器装git，然后用git拉取https://github.com/huggingface/peft.git 然后去安装peft还是指装git插件的同时，再装peft.git库

**Comment by lizhao-8202** [comment]
如果是装git只是拉取peft.git没必要装，比较迷糊

**Comment by fjiangAI** [comment]
> 咨询下。在requirements.txt中，有git+https://github.com/huggingface/peft.git 是表示在机器装git，然后用git拉取https://github.com/huggingface/peft.git 然后去安装peft还是指装git插件的同时，再装peft.git库

这个是pip install -r requirements.txt时候使用的，整个requirements.txt是使用pipreqs库自动导出的。
感谢提醒。

**Comment by lizhao-8202** [comment]
明白了，感谢感谢

**Comment by lizhao-8202** [comment]
解决
